name: 发布

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置 JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: 授予gradlew执行权限
      run: chmod +x gradlew
    
    - name: 构建可执行 JAR
      run: ./gradlew shadowJar --no-daemon
    
    - name: 获取版本号
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: 创建 Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*-all.jar
        generate_release_notes: true
        draft: false
        prerelease: false
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## OpenBMCLAPI Kotlin Agent ${{ steps.get_version.outputs.VERSION }}
          
          ### 下载
          下载 `openbmclapi-agent-*-all.jar` 文件即可运行。
          
          ### 运行方式
          ```bash
          java -jar openbmclapi-agent-*-all.jar
          ```
          
          ### 配置
          请参考 README.md 进行配置。
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
